version: 2
updates:
  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    reviewers:
      - "greenstevester"
    assignees:
      - "greenstevester"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    versioning-strategy: "increase"
    groups:
      # Group all non-security updates together
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "*eslint*"
          - "prettier"
          - "jest"
          - "typescript"
          - "@semantic-release/*"
          - "semantic-release"
        update-types:
          - "minor"
          - "patch"
      # Group dev dependencies
      development-dependencies:
        patterns:
          - "@types/*"
          - "*eslint*"
          - "prettier"
          - "jest"
          - "typescript"
          - "@semantic-release/*"
          - "semantic-release"
          - "ts-*"
          - "nodemon"
          - "npm-check-updates"
        update-types:
          - "minor"
          - "patch"
    # Security updates should always be individual PRs
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    reviewers:
      - "greenstevester"
    assignees:
      - "greenstevester"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    labels:
      - "github-actions"
      - "dependencies"
      - "automated"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 3
    reviewers:
      - "greenstevester"
    assignees:
      - "greenstevester"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    labels:
      - "docker"
      - "dependencies"
      - "automated" 
