name: Documentation Issue
description: Report missing, incorrect, or unclear documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
assignees:
  - greenstevester
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear documentation is essential for a good developer experience.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this documentation issue hasn't been reported before
          required: true
        - label: I have checked the latest version of the documentation
          required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect information
        - Unclear/confusing content
        - Outdated information
        - Broken links
        - Formatting issues
        - Typos/grammar
        - Example code issues
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation location
      description: Where is the documentation issue located?
      placeholder: |
        Please specify:
        - File name (e.g., README.md, CLAUDE.md)
        - Section or heading
        - Line numbers if applicable
        - URL if it's in GitHub Pages/Wiki
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue description
      description: Describe the documentation issue in detail
      placeholder: |
        What's wrong with the current documentation?
        What information is missing or incorrect?
        What was confusing or unclear?
    validations:
      required: true

  - type: textarea
    id: expected-content
    attributes:
      label: Expected content
      description: What should the documentation say instead?
      placeholder: |
        Provide the correct information or suggest how the documentation should be improved.
        Include specific wording if you have suggestions.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Additional context about this documentation issue
      placeholder: |
        - How did you discover this issue?
        - What were you trying to accomplish?
        - How did the current documentation fail to help you?
    validations:
      required: false

  - type: dropdown
    id: audience
    attributes:
      label: Target audience
      description: Who would benefit from fixing this documentation?
      options:
        - New users/beginners
        - Experienced developers
        - Contributors
        - All users
        - Specific use case (please specify in additional context)
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help improve the documentation?
      options:
        - label: I would be willing to submit a pull request to fix this documentation issue
          required: false